### ISSUE TITLE
Header Font is DEAD

### ISSUE THREAD

**Issue by oblivionmgd** [oblivionmgd/ARMap#6]
[Montserrat](https://fonts.google.com/specimen/Montserrat)のBold使って

**Comment by Hoppy-beginner** [comment]
<link href="https://fonts.googleapis.com/css?family=Open+Sans:700&display=swap" rel="stylesheet">を6行目に追加しました。

**Comment by oblivionmgd** [comment]
直ってねぇからプルリクするならやって

**Comment by Hoppy-beginner** [comment]
変えた
